---
- name: Ensure local Ansible Facts dir exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Read product UUID (may not exist on some platforms)
  register: _hostsync_product_uuid_raw
  become: true
  ansible.builtin.slurp:
    src: /sys/class/dmi/id/product_uuid

- name: Read machine-id (may not exist in containers)
  register: _hostsync_machine_id_raw
  become: false
  ansible.builtin.slurp:
    src: /etc/machine-id

- name: Build host_identity base fields
  ansible.builtin.set_fact:
    _hostsync_host_identity_inventory_id: "{{ inventory_hostname }}"
    _hostsync_host_identity_hostname: "{{ ansible_hostname }}"
    _hostsync_host_identity_fqdn: "{{ ansible_fqdn | default(ansible_hostname) }}"
    _hostsync_host_identity_product_uuid: "{{ (_hostsync_product_uuid_raw.content | default('')) | b64decode | trim }}"
    _hostsync_host_identity_machine_id: "{{ (_hostsync_machine_id_raw.content | default('')) | b64decode | trim }}"

- name: Compute preferred_id (UUID -> machine-id -> FQDN)
  become: false
  ansible.builtin.set_fact:
    _hostsync_host_identity_preferred: >-
      {{
        _hostsync_host_identity_product_uuid
          if (_hostsync_host_identity_product_uuid | length) > 0 else
        (_hostsync_host_identity_machine_id
          if (_hostsync_host_identity_machine_id | length) > 0 else
          _hostsync_host_identity_fqdn)
      }}

- name: Write host_identity local fact (JSON)
  notify:
    - "Refresh facts"
  become: true
  ansible.builtin.copy:
    dest: /etc/ansible/facts.d/host_uuid.fact
    owner: root
    group: root
    mode: "0644"
    content: >-
      {{
        {
          "host_identity": {
            "inventory": _hostsync_host_identity_inventory_id,
            "hostname": _hostsync_host_identity_hostname,
            "fqdn": _hostsync_host_identity_fqdn,
            "product_uuid": _hostsync_host_identity_product_uuid,
            "machine_id": _hostsync_host_identity_machine_id,
            "preferred_id": _hostsync_host_identity_preferred
          }
        } | to_nice_json
      }}
