---

- name: "Hostsync.Preflight - Validate role variables have been set correctly"
  delegate_to: localhost
  become: false
  ansible.builtin.assert:
    that:
      - hostsync_options_uuid is defined and hostsync_options_uuid | bool is boolean

- name: "Hostsync.Preflight - Report options"
  ansible.builtin.debug:
    msg: "UUID Enabled: {{ hostsync_options_uuid }}"

- name: "Hostsync.Preflight - Check required Netbox information has been set"
  delegate_to: localhost
  become: false
  ansible.builtin.assert:
    that:
      - hostsync_netbox_api is defined and hostsync_netbox_api| length > 0
      - hostsync_netbox_api_key is defined and hostsync_netbox_api_key | length > 0

- name: "Hostsync.Preflight - Check that you can connect to NetBox"
  delegate_to: localhost
  become: false
  ansible.builtin.uri:
    url: "{{ hostsync_netbox_api }}"
    validate_certs: "{{ hostsync_netbox_validcert }}"

- name: "Hostsync.Preflight - Test NetBox API Key"
  delegate_to: localhost
  become: false
  ansible.builtin.uri:
    url: "{{ hostsync_netbox_api }}/api/"
    validate_certs: "{{ hostsync_netbox_validcert }}"
    method: GET
    return_content: true
    headers:
      Authorization: Token {{ hostsync_netbox_api_key }}
      Accept: application/json
  register: _hostsync_api_check
  failed_when:
    - "'Invalid token' in _hostsync_api_check.content"
    - "'Failed to establish connection to Netbox API' in _hostsync_api_check.content"
