---
hostsync_sfp_check: false

_hostsync_iftype_logic:
  ether:
    10000: "10GBASE-T (10GE)"
    5000: "5GBASE-T (5GE)"
    2500: "2.5GBASE-T (2.5GE)"
    1000: "1000BASE-T (1GE)"
    100: "100BASE-T1 (10/100ME Single Pair)"
  sfp:
    50000: "SFP56 (50GE)"
    25000: "SFP28 (25GE)"
  default: "Other"
hostsync_iftype_lookup: "{{ _hostsync_iftype_logic[hostsync_sfp_check.stdout][hostsync_diface_details.speed] | default(_hostsync_iftype_logic['default']) }}"  # noqa: yaml[line-length]

hostsync_interface_system:
  - lo

hostsync_interface_mgmt:
  - idrac

hostsync_interface_exclude: "{{ hostsync_interface_system + hostsync_interface_mgmt }}"

_hostsync_primary_ipv4_cidr_logic: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
