---
hostsync_vm_logic:
  platform: >-
    {{ ansible_facts['system'] | lower }}_
    {{ ansible_facts['distribution'] | lower }}
    {% if ansible_facts['distribution_major_version'] is defined %}
      _{{ ansible_facts['distribution_major_version'] }}
      {% if ansible_facts['distribution_minor_version'] is defined %}
        _{{ ansible_facts['distribution_minor_version'] }}
      {% endif %}
    {% endif %}
