---

# For a list of colors, see here: https://github.com/netbox-community/netbox/blob/v3.4.5/netbox/utilities/choices.py#L100-L127
- name: "NBConfig.Extra - Manage extra:tags"
  become: false
  loop: "{{ config_extras_tags }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - config_extras_tags is defined
  netbox.netbox.netbox_tag:
    netbox_url: "{{ config_netbox_api }}"
    netbox_token: "{{ config_netbox_api_key }}"
    validate_certs: "{{ config_netbox_validcert }}"
    data:
      name: "{{ item.name }}"  # Required
      slug: "{{ item.slug }}"  # Required
      description: "{{ item.description }}"  # Optional
      color: "{{ item.color | default('00ff00') }}"  # Required
    state: "{{ item.state | default('present') }}"  # Optional
