---

- name: "Fetch existing CI (device) information from NetBox"
  delegate_to: localhost
  connection: local
  become: false
  check_mode: true
  register: netbox_ci_info
  netbox.netbox.netbox_device:
    netbox_url: "{{ hostsync_netbox_api }}"
    netbox_token: "{{ hostsync_netbox_api_key }}"
    validate_certs: "{{ hostsync_netbox_validcert }}"
    data:
      name: "{{ hostsync_hostname }}"

- name: "Write new CI (device) information to existing record in NetBox"
  ansible.builtin.include_tasks: device/device_write.yml

- name: "Enumerate adapter {{ item }}"
  ansible.builtin.include_tasks: device/adapter.yml
  loop: "{{ hostsync_interfaces }}"
  when:
    - hostvars[hostsync_hostname]['ansible_%s' | format(item)]['type'] != 'bonding'

- name: "Enumerate bond {{ item }}"
  ansible.builtin.include_tasks: device/adapter.yml
  loop: "{{ hostsync_interfaces }}"
  when:
    - hostvars[hostsync_hostname]['ansible_%s' | format(item)]['type'] == 'bonding'
