---
hostsync_device_features:
  serial: true
  type: true
  # sfp: true  # Disabled due to removal of SFP detection logic
# hostsync_device_nvidiagpu: true  # unused

hostsync_device_custom_fields:
  ssh_host_key_ecdsa: "{{ ansible_ssh_host_key_ecdsa_public }}"
  ssh_host_key_ed25519: "{{ ansible_ssh_host_key_ed25519_public }}"
  # ssh_host_key_rsa_public: "{{ ansible_ssh_host_key_rsa_public }}"
  # os_version: "{{ hostsync_os_selection_slug }}"
  # gpu_count: "{{ nvgpu_count | default(omit) | int }}"
  # gpu_type: "{{ nvgpu_type | default(omit) }}"
  product_uuid: "{{ _hostsync_host_identity_product_uuid | default(omit) }}"
  machine_id: "{{ _hostsync_host_identity_machine_id | default(omit) }}"


# use this to override fields
hostsync_device_override:
  # type:
  # serial:
  # platform:

hostsync_interface_type_overrides: {}   # e.g. { enp5s0f0np0: '10gbase-x-sfpp' }
