---

- name: Write VM information
  delegate_to: localhost
  connection: local
  become: false
  when:
    - not ansible_check_mode | bool
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ hostsync_netbox_api }}"
    netbox_token: "{{ hostsync_netbox_api_key }}"
    validate_certs: "{{ hostsync_netbox_validcert }}"
    data:
      name: "{{ hostsync_hostname }}"
      platform: "{{ hostsync_os_selection_slug }}"
      custom_fields: "{{ hostsync_vm_custom_fields_mapping }}"
      # primary_ip4: "{{ hostsync_primary_ipv4 }}"  # No sense writing this as we required it to access the host in Netbox
      tags: "{{ (netbox_ci_info.virtual_machine.tags | default([])) + ((hostsync_add_tags) | default([])) }}"
    state: present


- name: Debug data
  delegate_to: localhost
  connection: local
  become: false
  when:
    - ansible_check_mode | bool
  ansible.builtin.debug:
    msg:
      - Data to be written
      - "------------------"
      - "name: {{ hostsync_hostname }}"
      - "platform: {{ hostsync_os_selection_slug }}"
      - "custom_fields: {{ hostsync_vm_custom_fields_mapping }}"
      - "tags: {{ (netbox_ci_info.virtual_machine.tags | default([])) + ((hostsync_add_tags) | default([])) }}"
      - ''
      - "Original Data"
      - "------------------"
      - "{{ netbox_ci_info.virtual_machine }}"
