---

- name: Create a choice set with choices
  become: false
  loop: "{{ config_extras_custom_field_choices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - config_extras_custom_field_choices is defined
    - item.extra_choices is defined or item.base_choices is defined
  netbox.netbox.netbox_custom_field_choice_set:
    netbox_url: "{{ config_netbox_api }}"
    netbox_token: "{{ config_netbox_api_key }}"
    validate_certs: "{{ config_netbox_validcert }}"
    data:
      name: "{{ item.name }}"
      description: "{{ item.description | default(omit) }}"
      order_alphabetically: "{{ item.order_alphabetically | default(omit) }}"
      base_choices: "{{ item.base_choices | default(omit) }}"
      extra_choices: "{{ item.extra_choices | default(omit) }}"


- name: "NBConfig.Extra - Manage extra:custom_fields v4"
  become: false
  loop: "{{ config_extras_custom_fields }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - config_netbox_version is version(4, '>=')
    - config_extras_custom_fields is defined
  netbox.netbox.netbox_custom_field:
    netbox_url: "{{ config_netbox_api }}"
    netbox_token: "{{ config_netbox_api_key }}"
    validate_certs: "{{ config_netbox_validcert }}"
    data:
      object_types: "{{ item.object_types }}"  # Netbox 4.0
      group_name: "{{ item.group_name }}"
      name: "{{ item.name }}"
      label: "{{ item.label }}"
      type: "{{ item.type }}"
      choice_set: "{{ item.choice_set | default(omit) }}"  # Optional
    state: "{{ item.state | default('present') }}"  # Optional

- name: "NBConfig.Extra - Manage extra:custom_fields v3"
  become: false
  loop: "{{ config_extras_custom_fields_v3 }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - config_netbox_version is version(3, '==')
    - config_extras_custom_fields_v3 is defined
  netbox.netbox.netbox_custom_field:
    netbox_url: "{{ config_netbox_api }}"
    netbox_token: "{{ config_netbox_api_key }}"
    validate_certs: "{{ config_netbox_validcert }}"
    data:
      content_types: "{{ item.content_types }}"
      group_name: "{{ item.group_name }}"
      name: "{{ item.name }}"
      label: "{{ item.label }}"
      type: "{{ item.type }}"
      ui_visibility: "{{ item.ui_visibility }}"
      choice_set: "{{ item.choice_set | default(omit) }}"  # Optional
    state: "{{ item.state | default('present') }}"  # Optional
