---
# tasks file for nbconfig

- name: "NBConfig.Main - Handoff to Preflight task"
  ansible.builtin.include_tasks: preflight.yml

- name: "NBConfig.Main - Handoff to extras:custom_fields task"
  ansible.builtin.include_tasks: extras/custom_fields.yml

- name: "NBConfig.Main - Handoff to extras:tags task"
  ansible.builtin.include_tasks: extras/tags.yml

- name: "NBConfig.Main - Handoff to organization task"
  ansible.builtin.include_tasks: organization.yml

- name: "NBConfig.Main - Handoff to dcim task"
  ansible.builtin.include_tasks: dcim.yml

- name: "NBConfig.Main - Handoff to ipam task"
  ansible.builtin.include_tasks: ipam.yml

- name: "NBConfig.Main - Handoff to virtualization task"
  ansible.builtin.include_tasks: virtualization.yml

- name: "NBConfig.Main - Handoff to extras:config_contexts task"
  ansible.builtin.include_tasks: extras/config_contexts.yml
