---
# tasks file for nbconfig

- name: Check required information has been set
  become: false
  ansible.builtin.assert:
    that:
      - config_netbox_api is defined and config_netbox_api| length > 0
      - config_netbox_api_key is defined and config_netbox_api_key | length > 0
      - config_tags_base is defined and config_tags_base | list
      - config_netbox_version is defined and config_netbox_version is version(3, '>=')

- name: Check that you can connect to NetBox
  become: false
  ansible.builtin.uri:
    url: "{{ config_netbox_api }}"
    validate_certs: "{{ config_netbox_validcert }}"

- name: Test NetBox API Key
  become: false
  ansible.builtin.uri:
    url: "{{ config_netbox_api }}/api/"
    validate_certs: "{{ config_netbox_validcert }}"
    method: GET
    return_content: true
    headers:
      Authorization: Token {{ config_netbox_api_key }}
      Accept: application/json
  register: _config_api_check
  failed_when:
    - "'Invalid token' in _config_api_check.content"
    - "'Failed to establish connection to Netbox API' in _config_api_check.content"
