---
# ------
# Cluster Management: https://docs.ansible.com/ansible/latest/collections/netbox/netbox/netbox_cluster_type_module.html
- name: "NBConfig.Virtualization - Manage virtualization:cluster_types"
  become: false
  loop: "{{ config_virtualization_cluster_types }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - config_virtualization_cluster_types is defined
  netbox.netbox.netbox_cluster_type:
    netbox_url: "{{ config_netbox_api }}"
    netbox_token: "{{ config_netbox_api_key }}"
    validate_certs: "{{ config_netbox_validcert }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      description: "{{ item.description }}"
      tags: "{{ (item.tags | default([])) + (config_tags_base | default([])) }}"  # Optional
      custom_fields: "{{ item.custom_fields | default(omit) }}"  # Optional - must be pre-defined
    state: "{{ item.state | default('present') }}"  # Optional

# Cluster Groups
- name: "NBConfig.Virtualization - Manage virtualization:cluster_groups"
  become: false
  loop: "{{ config_virtualization_cluster_groups }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - config_virtualization_cluster_groups is defined
  netbox.netbox.netbox_cluster_type:
    netbox_url: "{{ config_netbox_api }}"
    netbox_token: "{{ config_netbox_api_key }}"
    validate_certs: "{{ config_netbox_validcert }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      description: "{{ item.description }}"
      tags: "{{ (item.tags | default([])) + (config_tags_base | default([])) }}"  # Optional
      custom_fields: "{{ item.custom_fields | default(omit) }}"  # Optional - must be pre-defined
    state: "{{ item.state | default('present') }}"  # Optional


- name: "NBConfig.Virtualization - Manage virtualization:clusters"
  become: false
  loop: "{{ config_virtualization_clusters }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - config_virtualization_clusters is defined
  netbox.netbox.netbox_cluster:
    netbox_url: "{{ config_netbox_api }}"
    netbox_token: "{{ config_netbox_api_key }}"
    validate_certs: "{{ config_netbox_validcert }}"
    data:
      name: "{{ item.name }}"
      cluster_type: "{{ item.cluster_type }}"  # Required - Defined in config_virtualization_cluster_types
      cluster_group: "{{ item.cluster_group | default(omit) }}"  # Optional - Defined in config_virtualization_cluster_groups
      status: "{{ item.status | default('active') | lower }}"  # Required - planned | staging | active | decomissioning | retired
      description: "{{ item.description | default(omit) }}"
      scope_type: "{{ item.scope_type | default(omit) }}"  # Optional - dcim.location | dcim.rack | dcim.region | dcim.site | dcim.sitegroup
      scope: "{{ item.scope | default(omit) }}"  # Optional -  has to be defined in location, rack, region, site or sitegroup
      tenant: "{{ item.tenant | default(omit) }}"
      site: "{{ item.site | default(omit) }}"  # Optional - will be removed in 5.0.0
      tags: "{{ (item.tags | default([])) + (config_tags_base | default([])) }}"  # Optional
      custom_fields: "{{ item.custom_fields | default(omit) }}"  # Optional - must be pre-defined
    state: present
