---
config_dcim_device_interface_template:
  - name: "LAN"
    # description:   # Optional
    device_type: "dm_bfg_9000"
    enabled: true
    mgmt_only: false
    label: "LAN"
    # poe_mode: "{{ item.poe_mode | default(omit) }}"
    # poe_type: "{{ item.poe_type | default(omit) }}"
    type: "1000base-t"
