config_dcim_site_groups:
  - name: "Customer Sites"  # Required
    slug: "customer_sites"  # Required
    # description: ""  # Optional
    # parent_site_group: ""  # Optional
    # tags: ""  # Optional
    # custom_fields: ""  # Optional - must be pre-defined

  - name: "Branch Offices"  # Required
    slug: "branch_offices"  # Required
    # description: ""  # Optional
    parent_site_group: "customer_sites"  # Optional
    # tags: ""  # Optional
    # custom_fields: ""  # Optional - must be pre-defined


config_dcim_sites:
  - name: "DM-Albany"  # Required
    slug: "dm-albany"  # Required
    status: 'Active'  # Required - Planned | Staging | Active | Decomissioning | Retired
    # description:  # Optional
    region: 'us-ny'  # Optional - Must be defined in config_dcim_regions
    site_group: 'branch_offices'  # Optional - Must be defined in config_dcim_site_groups
    tenant: 'dunder-mifflin'  # Optional - Must be defined in Tenant
    # facility:  # Optional
    # asn: AS64514  # Optional
    time_zone: 'America/New York'  # Optional - Must be an official time zone designation
    physical_address: "Dunder-Mifflin Inc, Albany, New York, USA"  # Optional
    shipping_address: "Dunder-Mifflin Inc, Albany, New York, USA"  # Optional
    # latitude:   # Optional - Eight digits maximum
    # longitude:   # Optional - Eight digits maximum
    # tags:  # Optional - these are in addition to config_tags_base
    # custom_fields:  # Optional - must be pre-defined
