---
- name: Perform Host Sync
  hosts:
    - all

  gather_facts: true
  roles:
    - tfindley.netbox.hostsync

  vars:
    hostsync_netbox_api: "{{ lookup('env', 'NETBOX_API') }}"
    hostsync_netbox_api_key: "{{ lookup('env', 'NETBOX_API_KEY') }}"
    hostsync_netbox_validcert: "{{ lookup('env', 'NETBOX_VALID_HTTPS') | bool | default(true) }}"
    hostsync_hostname: "{{ inventory_hostname }}"


    hostsync_netbox_version: 4.3
    # hostsync_interface_skip_regex: '^(lo|docker0|veth.*|br-[0-9a-f]{12}|docker0)$'
    hostsync_sfp_check: true  # Defaults to true
    # this requires privilage elevation on the target machine which you may not want.
    hostsync_uuid: true  # Defaults to true
    # this requires privilage elevation on the target machine which you may not want.
