---
# defaults file for hostsync

hostsync_netbox_api: "{{ lookup('env', 'NETBOX_API') }}"
hostsync_netbox_api_key: "{{ lookup('env', 'NETBOX_API_KEY') }}"
hostsync_netbox_validcert: "{{ lookup('env', 'NETBOX_VALID_HTTPS') | bool | default(true) }}"
hostsync_hostname: "{{ inventory_hostname }}"

# ------
hostsync_device_serialnumber: true
hostsync_device_devicetype: true
hostsync_device_nvidiagpu: true

# ------
# OS Selection logic
# This is here so it can be overwritten on a per-host basis if needed.
hostsync_os_selection_slug: "{{ ansible_system | lower }}_{{ ansible_distribution | lower }}{% if ansible_distribution_major_version is defined %}_{{ ansible_distribution_major_version }}{% if ansible_distribution_minor_version is defined %}_{{ ansible_distribution_minor_version }}{% endif %}{% endif %}"  # noqa: yaml[line-length]

# ------
# Tagging for Devices/Virtual Machines
hostsync_os_tag: "os_{{ hostsync_os_selection_slug | default('unknown') }}"  # No need to do this twice so we use the OS selection slug var.

# In order to add tags to every system that has been synced, adjust this line
hostsync_add_tags:
  - 'ansible_inventoried'
  - "{{ hostsync_os_tag }}"

hostsync_vm_custom_fields_mapping:
  ssh_host_key_ecdsa: "{{ ansible_ssh_host_key_ecdsa_public }}"
  ssh_host_key_ed25519: "{{ ansible_ssh_host_key_ed25519_public }}"
  # ssh_host_key_rsa_public: "{{ ansible_ssh_host_key_rsa_public }}"
  os_version: "{{ hostsync_os_selection_slug }}"

hostsync_device_custom_fields_mapping:
  ssh_host_key_ecdsa: "{{ ansible_ssh_host_key_ecdsa_public }}"
  ssh_host_key_ed25519: "{{ ansible_ssh_host_key_ed25519_public }}"
  # ssh_host_key_rsa_public: "{{ ansible_ssh_host_key_rsa_public }}"
  os_version: "{{ hostsync_os_selection_slug }}"
  # gpu_count: "{{ nvgpu_count | default(omit) | int }}"
  # gpu_type: "{{ nvgpu_type | default(omit) }}"

# hostsync_set_primaryip: false
hostsync_primary_ipv4: "{{ ansible_default_ipv4.address }}/{{ _hostsync_primary_ipv4_cidr_logic | ansible.utils.ipaddr('prefix') }}"
